name: eve_helper
description: A tool for EVE Online.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_staggered_grid_view: ^0.3.2
  http: ^0.13.1
  intl: ^0.17.0
  syncfusion_flutter_charts: ^19.1.54+1
  syncfusion_flutter_core: ^19.1.54+1
  syncfusion_flutter_datagrid: ^19.1.54-beta.1
  tuple: ^2.0.0
  xml: ^5.0.2
  provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/Icons/UI/Industry/
    - assets/Icons/UI/Crimewatch/
    - assets/Icons/items/Brackets/
    - assets/Icons/UI/WindowIcons/
    - assets/databases/