name: eve_helper
description: A tool for EVE Online.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  charts_flutter: ^0.9.0
  flutter_staggered_grid_view: ^0.3.2
  http: ^0.12.2
  intl: ^0.16.1
  syncfusion_flutter_charts: ^18.4.33
  tuple: ^1.0.3
  xml: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/Icons/UI/Industry/
    - assets/Icons/UI/Crimewatch/
    - assets/Icons/items/Brackets/
    - assets/Icons/UI/WindowIcons/
    - assets/databases/